- docs/guide/debug.md
- docs/guide/plugin/development.md
> fix: fix images and links

- docs/guide/contribute/environment.md
- docs/guide/use/interpolation-flutter.md
> fix: fix fixed flutter version

- .umirc.ts
> feat: statistic

- docs/api/extension/sliver.md
- docs/guide/advanced/high-performance-list.md
> docs: update sliver docs.

- docs/guide.md
> docs: Cli -> CLI

- docs/guide/network.md
> fix: fix link.

- .umirc.ts
- docs/index.md
- package.json
> 增加 文本输入、修改样式以及跳转问题

- .umirc.ts
- docs/guide.md
- docs/guide/basic/animation.md
- docs/guide/basic/scrollable.md
- docs/guide/basic/touch.md
- docs/guide/development/difference-to-web.md
- docs/guide/development/state.md
- docs/index.md
> 增加动画、统一示例标准、使用 JSX 风格编写样式

- docs/development/extension/storage.md
AsyncStorage API 修正为 Promise  的
> docs: update promise

- docs/development/styles/difference.md
- docs/development/styles/layout.md
- docs/development/styles/sizing.md
- docs/development/styles/transform.md
增加 css none value 支持，对应 issue https://github.com/openkraken/kraken/pull/129
> docs: add css none value

- docs/guide/development/vue.md
> del vue createEvent docs

- docs/guide/basic/multimedia.md
Closes https://github.com/openkraken/website/issues/97
> fix: add autoplay to video demo

- docs/guide/basic/animation.md
- docs/guide/basic/scrollable.md
> feat: 增加动画demo

- docs/guide/advanced/high-performance-list.md
Close #107 , Demo OSS updated.
> docs: update demo.

- .umirc.ts
- docs/guide/faq.md
> feat: add faq 

- package.json
> fix: del dark mode

- .umirc.ts
> feat: modify english logo

- docs/guide/development/react.md
- docs/guide/development/vue.md
> fix: modify script tag

- docs/guide.en-US.md
- docs/guide.md
升级 PlayKraken 的版本到 1.1.0, 内置的 Flutter 升级到 2.2.2, Kraken 版本 0.8.0+2, 同时使用 NullSafety 构建
> chore: update play kraken version from 1.0.0 to 1.1.0

- .umirc.ts
- docs/guide/advanced/gesture-to-native.en-US.md
- docs/guide/advanced/gesture-to-native.md
> feat: add doc of widget touch api.

- docs/guide/contribute/development.en-US.md
- docs/guide/contribute/development.md
Fix https://github.com/openkraken/kraken/issues/521
> doc: update developerment

- docs/index.en-US.md
- docs/index.md
- src/layout.tsx
> docs: police record

- docs/guide/advanced/communicate-with-native.en-US.md
- docs/guide/advanced/communicate-with-native.md
relation https://github.com/openkraken/kraken/pull/732
> setMethodCallHandler rename to addMethodCallHandler

- docs/api/styles/border.en-US.md
- docs/api/styles/border.md
* 增加对于 border-radius 不支持 case 的说明。
> feat: add border-radius exception note.

- docs/guide/native/embedded-devtools.en-US.md
- docs/guide/native/embedded-devtools.md
Close https://github.com/openkraken/kraken/issues/1123
> docs: update devtool

- src/app.ts
> 根据浏览器语言切换网站语言

- .umirc.ts
- docs/api/styles/difference.en-US.md
- docs/api/styles/difference.md
- docs/api/styles/variables.en-US.md
- docs/api/styles/variables.md
- docs/guide/basic/difference-to-web.en-US.md
- docs/guide/basic/difference-to-web.md
1. 更新关于样式的描述，支持 link, style 标签加载样式  
2. 新增 CSS Variables 文档
> docs: update style, add css variable

- .umirc.ts
- docs/api/dom/document.en-US.md
- docs/api/dom/document.md
1. 增加 querySelector, querySelectorAll, getElementsByClassName  Close #203 
2. 增加 Wiki 入口 Close #202
> docs: add some document API

- docs/guide/advanced/widget-custom-element.en-US.md
- docs/guide/advanced/widget-custom-element.md
Custom element add dispatch event.
> feat: custom element add dispatch event

- docs/guide/advanced/widget-custom-element.en-US.md
- docs/guide/advanced/widget-custom-element.md
https://github.com/openkraken/kraken/pull/1362
> :sparkles: feat: modify propeties of WidgetElement to attributes.

- docs/guide.en-US.md
- docs/guide.md
- docs/guide/basic/animation.en-US.md
- docs/guide/basic/animation.md
- docs/guide/basic/color.en-US.md
- docs/guide/basic/color.md
- docs/guide/basic/layout.en-US.md
- docs/guide/basic/layout.md
- docs/guide/basic/multimedia.en-US.md
- docs/guide/basic/multimedia.md
- docs/guide/basic/sizing.en-US.md
- docs/guide/basic/sizing.md
- docs/guide/basic/style.en-US.md
- docs/guide/basic/style.md
- docs/guide/native/interpolation-flutter.en-US.md
- docs/guide/native/interpolation-flutter.md
- docs/index.en-US.md
- docs/index.md
- docs/layout.en-US.md
- docs/layout.md
> fix: fix demo url
